### PR TITLE
Add the normal map of the grass texture to the terrain+mark assets as static

### PR DESCRIPTION
**Pull request by TijmenW**

### CODE REVIEW

**Comment by TijmenW** [comment]
wa

**Comment by Kovadon** [comment]
?

**Comment by TijmenW** [comment]
I closed it, because I didn't really test the last commit, and thought it could mess up the lightning settings. (Was to lazy to wait till unity baked everything)
Don't say I didn't warn you if it does. :-)

**Comment by Kovadon** [comment]
I'll iron out the issues. How'd you find this project? Through the subreddit?

**Comment by TijmenW** [comment]
Reddit, yes.

**Comment by Kovadon** [comment]
Cool. What experience do you have with Unity if you dont me asking?

**Comment by TijmenW** [comment]
Nothing serious. I have a project/game-like thing with a lot of assert throw together, and know how to code, but nothing more than that.

**Comment by Kovadon** [comment]
Haha sounds like most of us working on this project. If your truly interested in helping out, feel free to message me on Reddit. I'll add you as a Mod and you can join the team discussion on Skype.

**Pull request merged**
