### PR TITLE
Fix charmander textures

### PR DESCRIPTION
**Pull request by TijmenW**
Charmander's textures were misaligned, this fixes it.
also removes glossiness + edit flames

### CODE REVIEW

**Comment by TijmenW** [comment]
The flame is a bit of a hack. 
Also, please test if the controls are still working. They should be.

**Comment by Kovadon** [comment]
will do

**Comment by Kovadon** [comment]
PS, I forgot to sync a few hours of work from my desktop, so I'll have to
do that later. If I revert your commit, it's just so the game files dont
break. Sorry, still learning github, good work though, glad your part of
the team :)

**Comment by TijmenW** [comment]
I agree, Git is complicated.
This commit isn't merged yet, and if you have problems, please don't merge it until you resolved it.

**Comment by Kovadon** [comment]
alright, hopefully I'll figure everything out as to stop stopping progress
haha

thanks again for helping out, much appreciated.

**Comment by TijmenW** [comment]
Because of #8

**Pull request closed without merging**
